// const NUMBER_OF_MONTHS_IN_MONTH_DAY_MODEL = 4;
const NUMBER_OF_YEARS_IN_YEAR_MONTH_MODEL = 2;
const NUMBER_OF_MONTHS_IN_MONTH_DAY_MODEL = NUMBER_OF_YEARS_IN_YEAR_MONTH_MODEL * 12;

const CELL_MONTH_WIDTH_PX = 120;
const CELL_MONTH_WIDTH_PX_SLICES = 31;
const CELL_MONTH_SPLITED_WIDTH_PX = Math.round(CELL_MONTH_WIDTH_PX / CELL_MONTH_WIDTH_PX_SLICES);

const DAYS_AFTER_TODAY_IN_MONTH_DAY_MODEL = 4;
const MONTHS_AFTER_TODAY_IN_YEAR_MONTH_MODEL = 1;

const TOTAL_CELLS_IN_MONTH_DAY_MODEL = NUMBER_OF_MONTHS_IN_MONTH_DAY_MODEL * 31;
const TOTAL_MONTHS_IN_YEAR_MONTH_MODEL = NUMBER_OF_YEARS_IN_YEAR_MONTH_MODEL * 12;

export const MAIN_TABLE = {
  CELL_HEIGHT_PX: 28,
  CELL_MONTH_WIDTH_PX,
  CELL_MONTH_WIDTH_PX_SLICES,
  CELL_MONTH_SPLITED_WIDTH_PX,
  CELL_DAY_WIDTH_PX: 32,
  CELL_BORDER_COLOR: '#ddd',
  CELL_BACKGROUND_COLOR: '#fff',

  TOTAL_ROWS: 2,//10,
  NUMBER_OF_MONTHS_IN_MONTH_DAY_MODEL,
  NUMBER_OF_YEARS_IN_YEAR_MONTH_MODEL,

  DAYS_AFTER_TODAY_IN_MONTH_DAY_MODEL,
  MONTHS_AFTER_TODAY_IN_YEAR_MONTH_MODEL,

  TOTAL_CELLS_IN_MONTH_DAY_MODEL,
  TOTAL_MONTHS_IN_YEAR_MONTH_MODEL,

  // TODAY_COLUMN: 
  //   (TOTAL_MONTHS_IN_YEAR_MONTH_MODEL + MONTHS_AFTER_TODAY_IN_YEAR_MONTH_MODEL) 
  //   * CELL_MONTH_WIDTH_PX_SLICES - CELL_MONTH_WIDTH_PX_SLICES,
  FIRST_DAY_COLUMN: 0,
  LAST_DAY_COLUMN: TOTAL_MONTHS_IN_YEAR_MONTH_MODEL * CELL_MONTH_WIDTH_PX_SLICES - 1,
};
