export const MAIN_TABLE = {
  CELL_HEIGHT_PX: 24,
  CELL_MONTH_WIDTH_PX: 100,
  CELL_DAY_WIDTH_PX: 32,
  CELL_BORDER_COLOR: '#ddd',
  CELL_BACKGROUND_COLOR: '#fff',

  NUMBER_OF_MONTHS_IN_MONTH_DAY_MODEL: 4,
  NUMBER_OF_YEARS_IN_YEAR_MONTH_MODEL: 2,

  DAYS_AFTER_TODAY_IN_MONTH_DAY_MODEL: 4,
  MONTHS_AFTER_TODAY_IN_YEAR_MONTH_MODEL: 1,
};


